name: Build NextJS application
on:
  push:
    branches:
      - master
jobs:
    build-project:
      name: Build NextJS application
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install NPM dependencies
          run: npm install
        - name: Build project
          run: npm run build